# Generated by Django 5.0.7 on 2024-07-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.Field()),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('traffic_load', models.IntegerField()),
            ],
        ),
    ]
