# Generated by Django 5.0.7 on 2024-07-15 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bridge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridge",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
